version: '3'

dotenv:
  - prod.env

tasks:
  install:
    desc: Install project with development tooling
    cmds:
      - uv sync --dev --frozen
      - uv pip install -e .
      - uv run pre-commit install

  deps:
    desc: Install runtime dependencies
    cmds:
      - uv pip install -r requirements.txt

  test:
    desc: Run the full test suite
    cmds:
      - uv run pytest

  lint:
    desc: Lint with Ruff
    cmds:
      - uv run ruff check .

  format:
    desc: Format code with Ruff and apply fixes
    cmds:
      - uv run ruff check . --fix
      - uv run ruff format .

  publish:
    desc: Build and publish the package to PyPI
    env:
      UV_PUBLISH_TOKEN: "{{.PYPI_TOKEN}}"
    cmds:
      - rm -rf dist build
      - uv build --no-sources
      - uv publish
