version: '3'

dotenv:
  - prod.env

tasks:
  install:
    desc: Install project with development tooling
    cmds:
      - uv sync --dev --frozen
      - uv pip install -e .
      - uv run pre-commit install

  deps:
    desc: Install runtime dependencies
    cmds:
      - uv sync --frozen

  test:
    desc: Run the full test suite
    cmds:
      - uv run pytest

  test:record:
    desc: Run the full test suite
    cmds:
      - docker compose up -d
      - uv run pytest --record-mode=all
      - docker compose down

  lint:
    desc: Lint with Ruff
    cmds:
      - uv run ruff check .

  format:
    desc: Format code with Ruff and apply fixes
    cmds:
      - uv run ruff check . --fix
      - uv run ruff format .

  publish:
    desc: Build and publish the package to PyPI
    env:
      UV_PUBLISH_TOKEN: "{{.PYPI_TOKEN}}"
    cmds:
      - |
        set -euo pipefail
        package_name=$(sed -n 's/^name\s*=\s*"\([^"]*\)".*/\1/p' pyproject.toml)
        package_version=$(sed -n 's/^version\s*=\s*"\([^"]*\)".*/\1/p' pyproject.toml)
        if [ -z "$package_name" ] || [ -z "$package_version" ]; then
          echo "Failed to read project name or version from pyproject.toml" >&2
          exit 1
        fi
        pypi_package_json=$(curl --silent --location --fail "https://pypi.org/pypi/${package_name}/json" 2>/dev/null || true)
        published_version_entry=""
        if [ -n "$pypi_package_json" ]; then
          published_version_entry=$(printf '%s' "$pypi_package_json" | grep -F '"'"$package_version"'"' || true)
        fi
        if [ -n "$published_version_entry" ]; then
          echo "Version $package_version of $package_name already exists on PyPI. Aborting." >&2
          exit 1
        fi
        echo "Version $package_version of $package_name is not published on PyPI yet. Continuing."
      - rm -rf dist build
      - uv build --no-sources
      - uv publish
